name: Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "release tag"
        required: true
      prerelease:
        description: "pre-release"
        type: boolean
        default: false
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}

    steps:
      - if: github.event_name == 'workflow_dispatch'
        run: |
          [ "${{ inputs.prerelease }}" = "true" ] && PRERELEASE=--prerelease
          gh release create ${{ inputs.release_tag }} $PRERELEASE --generate-notes

      - if: github.event_name == 'push'
        run: |
          [ "${{ inputs.prerelease }}" = "true" ] && PRERELEASE=--prerelease
          gh release create ${{ github.ref_name }} $PRERELEASE --generate-notes
