name: PR Labeler
on:
  pull_request_target:

jobs:
  labeler:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v5
        with:
          configuration-path: ".github/labeler.yaml"
